=== cuongth99999/BackendMidLevel/app/code/Magenest/XmlConfiguration/etc/myconfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="aclCustomer">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="resources">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element minOccurs="0" maxOccurs="unbounded" name="resource" type="aclCustomerResource" />
                                    </xs:sequence>
                                </xs:complexType>

                                <xs:unique name="uniqueResourceId">
                                    <xs:annotation>
                                        <xs:documentation>
                                            Attribute id is unique under all ACL Customer resources
                                        </xs:documentation>
                                    </xs:annotation>
                                    <xs:selector xpath=".//*"/>
                                    <xs:field xpath="@id"/>
                                </xs:unique>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="aclCustomerResource">
        <xs:annotation>
            <xs:documentation>
                ACL Resource. Recursive complex type
            </xs:documentation>
        </xs:annotation>

        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="resource" type="aclCustomerResource" />
            <xs:element name="customer_group" type="xs:int" minOccurs="0"/>
        </xs:sequence>

        <xs:attribute name="id" type="typeId" use="required" />
        <xs:attribute name="title" type="typeTitle" use="optional" />
        <xs:attribute name="translate" type="xs:string" use="optional" />
        <xs:attribute name="sortOrder" type="xs:int" use="optional" />
        <xs:attribute name="disabled" type="xs:boolean" use="optional" />
    </xs:complexType>

    <xs:simpleType name="typeId">
        <xs:annotation>
            <xs:documentation>
                Item id attribute can have only [a-z0-9/_]. Minimal length 3 characters. Case insensitive.
            </xs:documentation>
        </xs:annotation>

        <xs:restriction base="xs:string">
            <xs:pattern value="([A-Z]+[a-zA-Z0-9]{1,}){1,}_[A-Z]+[A-Z0-9a-z]{1,}::[A-Za-z_0-9]{1,}" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="typeTitle">
        <xs:annotation>
            <xs:documentation>
                Item title attribute minimal length 3 symbol
            </xs:documentation>
        </xs:annotation>

        <xs:restriction base="xs:string">
            <xs:minLength value="3" />
            <xs:maxLength value="50" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== cuongth99999/BackendMidLevel/app/code/Magenest/XmlConfiguration/etc/myconfig.xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magenest_XmlConfiguration:etc/myconfig.xsd">
    <aclCustomer>
        <resources>
            <resource id="Customer_Feature" title="Customer Features" sortOrder="10">
                <customer_group>0</customer_group>
                <resource id="Customer_Account" title="Edit Account Info" sortOrder="10">
                    <customer_group>1</customer_group>
                </resource>
                <resource id="Customer_Wishlist" title="Wishlist" sortOrder="20">
                    <customer_group>2</customer_group>
                </resource>
                <resource id="Customer_Newsletter" title="Newsletter" sortOrder="30">
                    <customer_group>3</customer_group>
                </resource>
                <resource id="Customer_Checkout" title="Checkout" sortOrder="40">
                    <customer_group>4</customer_group>
                </resource>
            </resource>
            <resource id="Customer_Feature_2" title="Customer Features 2" sortOrder="10">
                <customer_group>0</customer_group>
                <resource id="Customer_Account" title="Edit Account Info" sortOrder="10">
                    <customer_group>1</customer_group>
                </resource>
                <resource id="Customer_Checkout" title="Checkout" sortOrder="40">
                    <customer_group>4</customer_group>
                </resource>
            </resource>
        </resources>
    </aclCustomer>
</config>
